//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultikeysEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultikeysEditor.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose....
        /// </summary>
        public static string ChooseFile {
            get {
                return ResourceManager.GetString("ChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose file to assign to this key.
        /// </summary>
        public static string ChooseFileToAssignToThisKey {
            get {
                return ResourceManager.GetString("ChooseFileToAssignToThisKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current state: Paused.
        /// </summary>
        public static string CoreStatePaused {
            get {
                return ResourceManager.GetString("CoreStatePaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current state: Running.
        /// </summary>
        public static string CoreStateRunning {
            get {
                return ResourceManager.GetString("CoreStateRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current state: Stopped.
        /// </summary>
        public static string CoreStateStopped {
            get {
                return ResourceManager.GetString("CoreStateStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string DeadKeyReplacementFrom {
            get {
                return ResourceManager.GetString("DeadKeyReplacementFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacements.
        /// </summary>
        public static string DeadKeyReplacements {
            get {
                return ResourceManager.GetString("DeadKeyReplacements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string DeadKeyReplacementTo {
            get {
                return ResourceManager.GetString("DeadKeyReplacementTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments.
        /// </summary>
        public static string ExecutableKeyArguments {
            get {
                return ResourceManager.GetString("ExecutableKeyArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        public static string ExecutableKeyCommand {
            get {
                return ResourceManager.GetString("ExecutableKeyCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: .
        /// </summary>
        public static string KeyboardAlias {
            get {
                return ResourceManager.GetString("KeyboardAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change labels.
        /// </summary>
        public static string KeyboardControlChangeLogicalLayout {
            get {
                return ResourceManager.GetString("KeyboardControlChangeLogicalLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change layout.
        /// </summary>
        public static string KeyboardControlChangePhysicalLayout {
            get {
                return ResourceManager.GetString("KeyboardControlChangePhysicalLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete keyboard.
        /// </summary>
        public static string KeyboardControlDeleteKeyboard {
            get {
                return ResourceManager.GetString("KeyboardControlDeleteKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique id: .
        /// </summary>
        public static string KeyboardName {
            get {
                return ResourceManager.GetString("KeyboardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Any keyboard).
        /// </summary>
        public static string KeyboardNameDialogAnyKeyboard {
            get {
                return ResourceManager.GetString("KeyboardNameDialogAnyKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string KeyboardNameDialogFinish {
            get {
                return ResourceManager.GetString("KeyboardNameDialogFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect keyboard.
        /// </summary>
        public static string KeyboardNameDialogListenForInput {
            get {
                return ResourceManager.GetString("KeyboardNameDialogListenForInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press a key on the keyboard you wish to detect..
        /// </summary>
        public static string KeyboardNameDialogPressAnyKey {
            get {
                return ResourceManager.GetString("KeyboardNameDialogPressAnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use any keyboard.
        /// </summary>
        public static string KeyboardNameDialogUseAnyKeyboard {
            get {
                return ResourceManager.GetString("KeyboardNameDialogUseAnyKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string KeyboardNameEdit {
            get {
                return ResourceManager.GetString("KeyboardNameEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign command.
        /// </summary>
        public static string KeyOptionsAssignCommand {
            get {
                return ResourceManager.GetString("KeyOptionsAssignCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change modifier name.
        /// </summary>
        public static string KeyOptionsChangeModifierName {
            get {
                return ResourceManager.GetString("KeyOptionsChangeModifierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit command.
        /// </summary>
        public static string KeyOptionsEditCommand {
            get {
                return ResourceManager.GetString("KeyOptionsEditCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as modifier.
        /// </summary>
        public static string KeyOptionsRegisterModifier {
            get {
                return ResourceManager.GetString("KeyOptionsRegisterModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove command.
        /// </summary>
        public static string KeyOptionsRemoveCommand {
            get {
                return ResourceManager.GetString("KeyOptionsRemoveCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregister as modifier.
        /// </summary>
        public static string KeyOptionsUnregisterModifier {
            get {
                return ResourceManager.GetString("KeyOptionsUnregisterModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key press.
        /// </summary>
        public static string KeyPress {
            get {
                return ResourceManager.GetString("KeyPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key release.
        /// </summary>
        public static string KeyRelease {
            get {
                return ResourceManager.GetString("KeyRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new keyboard.
        /// </summary>
        public static string LayoutControlAddNewKeyboard {
            get {
                return ResourceManager.GetString("LayoutControlAddNewKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error during the program&apos;s execution. A log file could not be created. Error:.
        /// </summary>
        public static string LogFailedToCreateLog {
            get {
                return ResourceManager.GetString("LogFailedToCreateLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error during the program&apos;s execution. Could not write to log file. Error:.
        /// </summary>
        public static string LogFailedToWriteToLog {
            get {
                return ResourceManager.GetString("LogFailedToWriteToLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error during the program&apos;s execution. For details, see the log file at.
        /// </summary>
        public static string LogSeeLog {
            get {
                return ResourceManager.GetString("LogSeeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence.
        /// </summary>
        public static string MacroSequence {
            get {
                return ResourceManager.GetString("MacroSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string MenuFileClose {
            get {
                return ResourceManager.GetString("MenuFileClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string MenuFileNew {
            get {
                return ResourceManager.GetString("MenuFileNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        public static string MenuFileOpen {
            get {
                return ResourceManager.GetString("MenuFileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string MenuFileSave {
            get {
                return ResourceManager.GetString("MenuFileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as....
        /// </summary>
        public static string MenuFileSaveAs {
            get {
                return ResourceManager.GetString("MenuFileSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import....
        /// </summary>
        public static string MenuImportKeyboard {
            get {
                return ResourceManager.GetString("MenuImportKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifiers.
        /// </summary>
        public static string Modifiers {
            get {
                return ResourceManager.GetString("Modifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose which layout to print on the keys:.
        /// </summary>
        public static string PromptChangeLayoutChooseLogicalLayout {
            get {
                return ResourceManager.GetString("PromptChangeLayoutChooseLogicalLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the physical layout:.
        /// </summary>
        public static string PromptChangeLayoutChoosePhysicalLayout {
            get {
                return ResourceManager.GetString("PromptChangeLayoutChoosePhysicalLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string PromptChangeLayoutConfirm {
            get {
                return ResourceManager.GetString("PromptChangeLayoutConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use big return key.
        /// </summary>
        public static string PromptChangeLayoutUseBigEnter {
            get {
                return ResourceManager.GetString("PromptChangeLayoutUseBigEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name already exists..
        /// </summary>
        public static string PromptChangeModifierNameAlreadyExists {
            get {
                return ResourceManager.GetString("PromptChangeModifierNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string PromptChangeModifierNameConfirm {
            get {
                return ResourceManager.GetString("PromptChangeModifierNameConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, input a valid name..
        /// </summary>
        public static string PromptChangeModifierNameInvalidText {
            get {
                return ResourceManager.GetString("PromptChangeModifierNameInvalidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a new name for the modifier:.
        /// </summary>
        public static string PromptChangeModifierNameText {
            get {
                return ResourceManager.GetString("PromptChangeModifierNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments to pass to file:.
        /// </summary>
        public static string PromptExecutableArguments {
            get {
                return ResourceManager.GetString("PromptExecutableArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the file to open:.
        /// </summary>
        public static string PromptExecutableFilename {
            get {
                return ResourceManager.GetString("PromptExecutableFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new keystroke.
        /// </summary>
        public static string PromptMacroAddKeystroke {
            get {
                return ResourceManager.GetString("PromptMacroAddKeystroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string PromptMacroAddKeystrokeConfirm {
            get {
                return ResourceManager.GetString("PromptMacroAddKeystrokeConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string PromptMacroColumnHeaderCode {
            get {
                return ResourceManager.GetString("PromptMacroColumnHeaderCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key down.
        /// </summary>
        public static string PromptMacroColumnHeaderDown {
            get {
                return ResourceManager.GetString("PromptMacroColumnHeaderDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PromptMacroColumnHeaderName {
            get {
                return ResourceManager.GetString("PromptMacroColumnHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string PromptMacroKeystrokeDown {
            get {
                return ResourceManager.GetString("PromptMacroKeystrokeDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string PromptMacroKeystrokeUp {
            get {
                return ResourceManager.GetString("PromptMacroKeystrokeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to existing modifier:.
        /// </summary>
        public static string PromptModifierAddToExistingModifier {
            get {
                return ResourceManager.GetString("PromptModifierAddToExistingModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register modifier.
        /// </summary>
        public static string PromptModifierConfirm {
            get {
                return ResourceManager.GetString("PromptModifierConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New modifier:.
        /// </summary>
        public static string PromptModifierNewModfier {
            get {
                return ResourceManager.GetString("PromptModifierNewModfier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Command.
        /// </summary>
        public static string PromptNewCommandAssignCommand {
            get {
                return ResourceManager.GetString("PromptNewCommandAssignCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert one or more Unicode characters:.
        /// </summary>
        public static string PromptUnicodePromptInput {
            get {
                return ResourceManager.GetString("PromptUnicodePromptInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block: .
        /// </summary>
        public static string PromptUnicodeSelectedCharacterBlock {
            get {
                return ResourceManager.GetString("PromptUnicodeSelectedCharacterBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category: .
        /// </summary>
        public static string PromptUnicodeSelectedCharacterCategory {
            get {
                return ResourceManager.GetString("PromptUnicodeSelectedCharacterCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codepoint: .
        /// </summary>
        public static string PromptUnicodeSelectedCharacterCodepoint {
            get {
                return ResourceManager.GetString("PromptUnicodeSelectedCharacterCodepoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: .
        /// </summary>
        public static string PromptUnicodeSelectedCharacterName {
            get {
                return ResourceManager.GetString("PromptUnicodeSelectedCharacterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger repeatedly when key is pressed down.
        /// </summary>
        public static string PromptUnicodeTriggerOnRepeat {
            get {
                return ResourceManager.GetString("PromptUnicodeTriggerOnRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dead key.
        /// </summary>
        public static string ReadableNameDeadkey {
            get {
                return ResourceManager.GetString("ReadableNameDeadkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command key.
        /// </summary>
        public static string ReadableNameExecutablekey {
            get {
                return ResourceManager.GetString("ReadableNameExecutablekey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macro key.
        /// </summary>
        public static string ReadableNameMacroKey {
            get {
                return ResourceManager.GetString("ReadableNameMacroKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier key.
        /// </summary>
        public static string ReadableNameModifier {
            get {
                return ResourceManager.GetString("ReadableNameModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text key.
        /// </summary>
        public static string ReadableNameUnicodeKey {
            get {
                return ResourceManager.GetString("ReadableNameUnicodeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This key is not remapped..
        /// </summary>
        public static string ThisKeyIsNotRemapped {
            get {
                return ResourceManager.GetString("ThisKeyIsNotRemapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual key code.
        /// </summary>
        public static string VirtualKeyCode {
            get {
                return ResourceManager.GetString("VirtualKeyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: This key is remapped in other layers. Setting this key as modifier will take precedence over those remaps. Proceed?.
        /// </summary>
        public static string WarningModifierOverridesCommands {
            get {
                return ResourceManager.GetString("WarningModifierOverridesCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An executable file must be selected..
        /// </summary>
        public static string WarningNoFileSelected {
            get {
                return ResourceManager.GetString("WarningNoFileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No layout is currently open..
        /// </summary>
        public static string WarningNoLayout {
            get {
                return ResourceManager.GetString("WarningNoLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this command?.
        /// </summary>
        public static string WarningRemoveCommand {
            get {
                return ResourceManager.GetString("WarningRemoveCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregister this modifier?.
        /// </summary>
        public static string WarningRemoveModifier {
            get {
                return ResourceManager.GetString("WarningRemoveModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must save the layout in order to use it. Save it now?.
        /// </summary>
        public static string WarningSaveLayoutToStart {
            get {
                return ResourceManager.GetString("WarningSaveLayoutToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved changes will be lost. Proceed?.
        /// </summary>
        public static string WarningWillOverwriteWorkingLayout {
            get {
                return ResourceManager.GetString("WarningWillOverwriteWorkingLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change keyboard layout.
        /// </summary>
        public static string WindowTitleChangeLayout {
            get {
                return ResourceManager.GetString("WindowTitleChangeLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change modifier name.
        /// </summary>
        public static string WindowTitleChangeModifierName {
            get {
                return ResourceManager.GetString("WindowTitleChangeModifierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit command.
        /// </summary>
        public static string WindowTitleEditCommandDialog {
            get {
                return ResourceManager.GetString("WindowTitleEditCommandDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit keyboard&apos;s name.
        /// </summary>
        public static string WindowTitleKeyboardAliasDialog {
            get {
                return ResourceManager.GetString("WindowTitleKeyboardAliasDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit keyboard&apos;s unique id.
        /// </summary>
        public static string WindowTitleKeyboardNameDialog {
            get {
                return ResourceManager.GetString("WindowTitleKeyboardNameDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multikeys - Main Window.
        /// </summary>
        public static string WindowTitleMainWindow {
            get {
                return ResourceManager.GetString("WindowTitleMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New command.
        /// </summary>
        public static string WindowTitleNewCommandDialog {
            get {
                return ResourceManager.GetString("WindowTitleNewCommandDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register key as modifier.
        /// </summary>
        public static string WindowTitleNewModifierDialog {
            get {
                return ResourceManager.GetString("WindowTitleNewModifierDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
