//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultikeysGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultikeysGUI.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string DeadKeyReplacementFrom {
            get {
                return ResourceManager.GetString("DeadKeyReplacementFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacements.
        /// </summary>
        public static string DeadKeyReplacements {
            get {
                return ResourceManager.GetString("DeadKeyReplacements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string DeadKeyReplacementTo {
            get {
                return ResourceManager.GetString("DeadKeyReplacementTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments.
        /// </summary>
        public static string ExecutableKeyArguments {
            get {
                return ResourceManager.GetString("ExecutableKeyArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        public static string ExecutableKeyCommand {
            get {
                return ResourceManager.GetString("ExecutableKeyCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: .
        /// </summary>
        public static string KeyboardName {
            get {
                return ResourceManager.GetString("KeyboardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign command.
        /// </summary>
        public static string KeyOptionsAssignCommand {
            get {
                return ResourceManager.GetString("KeyOptionsAssignCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit command.
        /// </summary>
        public static string KeyOptionsEditCommand {
            get {
                return ResourceManager.GetString("KeyOptionsEditCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as modifier.
        /// </summary>
        public static string KeyOptionsRegisterModifier {
            get {
                return ResourceManager.GetString("KeyOptionsRegisterModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove command.
        /// </summary>
        public static string KeyOptionsRemoveCommand {
            get {
                return ResourceManager.GetString("KeyOptionsRemoveCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregister as modifier.
        /// </summary>
        public static string KeyOptionsUnregisterModifier {
            get {
                return ResourceManager.GetString("KeyOptionsUnregisterModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key press.
        /// </summary>
        public static string KeyPress {
            get {
                return ResourceManager.GetString("KeyPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key release.
        /// </summary>
        public static string KeyRelease {
            get {
                return ResourceManager.GetString("KeyRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence.
        /// </summary>
        public static string MacroSequence {
            get {
                return ResourceManager.GetString("MacroSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string MenuFileClose {
            get {
                return ResourceManager.GetString("MenuFileClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        public static string MenuFileOpen {
            get {
                return ResourceManager.GetString("MenuFileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string MenuFileSave {
            get {
                return ResourceManager.GetString("MenuFileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as....
        /// </summary>
        public static string MenuFileSaveAs {
            get {
                return ResourceManager.GetString("MenuFileSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifiers.
        /// </summary>
        public static string Modifiers {
            get {
                return ResourceManager.GetString("Modifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign command.
        /// </summary>
        public static string PromptUnicodeConfirm {
            get {
                return ResourceManager.GetString("PromptUnicodeConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert one or more Unicode characters:.
        /// </summary>
        public static string PromptUnicodePromptInput {
            get {
                return ResourceManager.GetString("PromptUnicodePromptInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block: .
        /// </summary>
        public static string PromptUnicodeSelectedCharacterBlock {
            get {
                return ResourceManager.GetString("PromptUnicodeSelectedCharacterBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category: .
        /// </summary>
        public static string PromptUnicodeSelectedCharacterCategory {
            get {
                return ResourceManager.GetString("PromptUnicodeSelectedCharacterCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codepoint: .
        /// </summary>
        public static string PromptUnicodeSelectedCharacterCodepoint {
            get {
                return ResourceManager.GetString("PromptUnicodeSelectedCharacterCodepoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: .
        /// </summary>
        public static string PromptUnicodeSelectedCharacterName {
            get {
                return ResourceManager.GetString("PromptUnicodeSelectedCharacterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger repeatedly when key is pressed down.
        /// </summary>
        public static string PromptUnicodeTriggerOnRepeat {
            get {
                return ResourceManager.GetString("PromptUnicodeTriggerOnRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dead key.
        /// </summary>
        public static string ReadableNameDeadkey {
            get {
                return ResourceManager.GetString("ReadableNameDeadkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command key.
        /// </summary>
        public static string ReadableNameExecutablekey {
            get {
                return ResourceManager.GetString("ReadableNameExecutablekey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macro key.
        /// </summary>
        public static string ReadableNameMacroKey {
            get {
                return ResourceManager.GetString("ReadableNameMacroKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier key.
        /// </summary>
        public static string ReadableNameModifier {
            get {
                return ResourceManager.GetString("ReadableNameModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text key.
        /// </summary>
        public static string ReadableNameUnicodeKey {
            get {
                return ResourceManager.GetString("ReadableNameUnicodeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This key is not remapped..
        /// </summary>
        public static string ThisKeyIsNotRemapped {
            get {
                return ResourceManager.GetString("ThisKeyIsNotRemapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual key code.
        /// </summary>
        public static string VirtualKeyCode {
            get {
                return ResourceManager.GetString("VirtualKeyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit command.
        /// </summary>
        public static string WindowTitleEditCommandDialog {
            get {
                return ResourceManager.GetString("WindowTitleEditCommandDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New command.
        /// </summary>
        public static string WindowTitleNewCommandDialog {
            get {
                return ResourceManager.GetString("WindowTitleNewCommandDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
